"""Pando-Agent 全仓 related/hybrid 评测 ground truth（跨模块，非单目录）。"""
from __future__ import annotations
from tests.scenarios.framework.case_spec import PathSetCase


PANDO_RELATED_CASES = [
    PathSetCase(
        case_id="pando.full.exact.ReActAgent",
        description="全仓精确符号 ReActAgent",
        expected_paths=["app/agents/core/react.py"],
        min_precision=0.5,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["ReActAgent"], "expect_exact": True},
    ),
    PathSetCase(
        case_id="pando.full.exact.BaseAgent",
        description="全仓精确符号 BaseAgent",
        expected_paths=["app/agents/core/base.py"],
        min_precision=0.5,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["BaseAgent"], "expect_exact": True},
    ),
    PathSetCase(
        case_id="pando.full.exact.ContextBuilder",
        description="全仓精确符号 ContextBuilder",
        expected_paths=["app/agents/context/context.py"],
        min_precision=0.4,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["ContextBuilder"], "expect_exact": True},
    ),
    PathSetCase(
        case_id="pando.full.exact.PlanningAgent",
        description="全仓精确符号 PlanningAgent",
        expected_paths=["app/agents/plan/planning.py"],
        min_precision=0.4,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["PlanningAgent"], "expect_exact": True},
    ),
    PathSetCase(
        case_id="pando.full.exact.LangGraphExecutor",
        description="全仓精确符号 LangGraphExecutor",
        expected_paths=["app/agents/plan/langraph_excutor.py"],
        min_precision=0.4,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["LangGraphExecutor"], "expect_exact": True},
    ),
    PathSetCase(
        case_id="pando.full.exact.EmbeddingModelFactory",
        description="全仓精确符号 EmbeddingModelFactory",
        expected_paths=["app/infrastructure/llms/embedding_models/factory.py"],
        min_precision=0.3,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["EmbeddingModelFactory"], "expect_exact": True},
    ),
    PathSetCase(
        case_id="pando.full.exact.OpenAIModels",
        description="全仓精确符号 OpenAIModels",
        expected_paths=["app/infrastructure/llms/chat_models/openai_llm.py"],
        min_precision=0.3,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["OpenAIModels"], "expect_exact": True},
    ),
    PathSetCase(
        case_id="pando.full.path.jwt_validator",
        description="路径段 jwt_validator 应命中鉴权模块",
        expected_paths=["app/utils/auth/jwt_validator.py"],
        min_precision=0.25,
        min_recall=1.0,
        top_k=10,
        extra={"keywords": ["jwt_validator"]},
    ),
    PathSetCase(
        case_id="pando.full.semantic.memory",
        description="语义检索默认记忆实现",
        expected_paths=["app/agents/memorys/default/memory.py"],
        min_precision=0.1,
        min_recall=1.0,
        top_k=15,
        extra={"keywords": ["default memory extract prompt for agent long-term memory"]},
    ),
    PathSetCase(
        case_id="pando.full.semantic.websocket",
        description="语义检索 websocket 通道",
        expected_paths=["app/channel/websocket/websocket.py"],
        min_precision=0.1,
        min_recall=1.0,
        top_k=15,
        extra={"keywords": ["websocket channel connection manager for realtime messages"]},
    ),
]
